version: '3.4'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
    networks:
      - production-network

  server:
    build: ./server
    container_name: server
    ports:
      - "3001:3001"
    environment:
      - MONGO_DB=${MONGO_DB}
      - REDIS_URI=${REDIS_URI}
    links:
      - mongodb
    networks:
      - production-network

  client:
    build: ./client
    container_name: client
    ports:
      - 5173:5173
    links:
      - server
    networks:
      - production-network

networks: 
    production-network:
        driver: bridge

volumes:
  data: {}